# Generated by Django 4.1.5 on 2023-01-31 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cells', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cells',
            options={'ordering': ('cell_name',)},
        ),
        migrations.AlterField(
            model_name='cells',
            name='cell_name',
            field=models.CharField(max_length=3, unique=True),
        ),
    ]
