# Generated by Django 4.1.5 on 2023-01-04 20:35

import backend.base.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cells', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40, validators=[backend.base.validators.validate_only_letters, django.core.validators.MinLengthValidator(2)], verbose_name='First Name')),
                ('last_name', models.CharField(max_length=40, validators=[backend.base.validators.validate_only_letters, django.core.validators.MinLengthValidator(2)], verbose_name='Last Name')),
                ('emp_id', models.CharField(max_length=7, unique=True, verbose_name='Employee Id')),
                ('cell', models.ManyToManyField(to='cells.cells')),
            ],
            options={
                'ordering': ('first_name',),
            },
        ),
    ]
